### ISSUE TITLE
How many memory will googlenet cost?

### ISSUE THREAD

**Issue by lucasjinreal** [krasin/MetalDetector#4]
Did you test that? I'd like try your code on iPhone7

**Comment by krasin** [comment]
I don't have numbers of top of my mind, so it's worth trying to measure it yourself. iPhone 7 should be fine, but I only tested it on iPhone 6S and iPhone 6.

**Comment by krasin** [comment]
Also, I need to point out that TensorFlow mobile support is superior to what I did here (I did it before Tensorflow was even announced). So, you might want to skip this repo altogether.

For a decent pretrained TensorFlow model that might be a good fit for replacing this GoogLeNet, take a look at https://github.com/openimages/dataset/wiki/Running-a-pretrained-classifier that I released as a part of [Open Images](https://research.googleblog.com/2016/09/introducing-open-images-dataset.html).

**Comment by lucasjinreal** [comment]
You mean tensorflow has a greater performance on this method? Then maybe I should learn tensorflow.

**Comment by krasin** [comment]
Learning TensorFlow is a safe bet, for sure. :)

**Comment by lucasjinreal** [comment]
But tensorflow in PC somewhere slow then other frameworks, on mobile platform maybe tensorflow has some advantages.

**Comment by krasin** [comment]
Only very first versions of Tensorflow were noticeably slower than other frameworks. Once the team updated their cudnn version, Tensorflow performance has become quite decent: https://github.com/soumith/convnet-benchmarks

As for the mobile performance, this is a completely different beast, as the models can be optimized given specific shapes and weights, and appropriate quantization performed. This is what I did in this repo, and this is what Pete Warden explains in [Tensorflow for Mobile Poets](https://petewarden.com/2016/09/27/tensorflow-for-mobile-poets/), and this is what [Tensorflow XLA](https://www.tensorflow.org/versions/master/experimental/xla/) compiler is for.

As a somewhat related demo of Tensorflow performance on mobile, please, see the video demo in Qualcomm's press release: [TensorFlow machine learning now optimized for the Snapdragon 835 and Hexagon 682 DSP](https://www.qualcomm.com/news/snapdragon/2017/01/09/tensorflow-machine-learning-now-optimized-snapdragon-835-and-hexagon-682). They achieve 10 FPS on GoogLeNet (the same net as in the current repo)
